### ISSUE TITLE
1_2_autograd_tutorial_jp.ipynb

### ISSUE THREAD

**Issue by jupiro** [YutaroOgawa/pytorch_tutorials_jp#14]
> (日本語訳注：英語版は  𝑧𝑖∣∣𝑥𝑖=1=27 .となっていますが、18と思われます。）

と書いておられますが， 27 のままで正しいと思います．

どうして， 18 と思われましたか？

**Comment by YutaroOgawa** [comment]
@jupiro さま

ご指摘ありがとうございます。

私の勘違いでしょうか。整理させてください（恥ずかしい。申し訳ございません）。
チュートリアルのセルにもございますが、

print(x.grad)　は　各要素が4.5となっています。

これは以下私の解釈では

y_i  = x_i +2 
z_i = 3(y_i)^2
out_i =1/4 *z_i   ※meanをとるため、各要素は1/4される 

のため、
z_i = 3(x_i+2)^2 

であり、
∂z_i/∂x_i = 6*(x_i+2)

となる。x_i = 1のときは、

∂z_i/∂x_i∣(x_i=1)= 6*(1+2)=18

であり、

∂o_i / ∂xi∣(x_i=1) =   1/4 * 6*(x_i+2) ∣(x_i=1) 
                            = 3/2 *3 = 9/2 =4.5

だと、認識しております。


数式をダイレクトに書いていて見づらく大変申し訳ございません。

私の勘違い部分をご指導いただけますでしょうか（恥ずかしい、大変申し訳ございません。）
どうぞよろしくお願いいたします

**Comment by jupiro** [comment]
この notebook の式は，
 z_i (x_i = 1)

ですので，
3 * (x_i + 2) ^2 ( x_i = 1) = 3*(1 +2) ^2 = 27

です．18 となるのは，
∂z_i/∂x_i∣(x_i=1)= 6*(1+2)=18
で式が異なるような気がしています．

**Comment by YutaroOgawa** [comment]
@jupiro さま

なるほど。左辺勘違いしていました。

z_i | (x_i = 1) = 27

∂z_i/∂x_i∣(x_i=1) = 18

で、今、日本語のチュートリアルは

z_i | (x_i = 1) = 18

で、おかしいですね。

貴重な時間をいただき、大変申し訳ございません。

誠にありがとうございます。

PRもMergeします。

早朝よりお付き合いいただき、誠にありがとうございます！
