### ISSUE TITLE
誤字の報告

### ISSUE THREAD

**Issue by kr-tukimi** [YutaroOgawa/pytorch_tutorials_jp#16]
失礼します。
本リポジトリ内のREADME.mdとindex.htmlの [2] の

> 本サイトでは 「Gooogle Colaboratory ファイル」で、チュートリアルの日本語訳を用意しております。

ですが、Gooogleではなくて、Googleなのではないでしょうか？
失礼しました。

**Comment by YutaroOgawa** [comment]
@kr-tukimi さま

ご指摘いただき、誠にありがとうございます。
細かな点まで丁寧にご覧いただき、とても助かります

Oが多いですねwww 恥ずかしい。。。

以下修正しました！

https://github.com/YutaroOgawa/pytorch_tutorials_jp/commit/238de125717242e75cc071a0e2721dbc518ba56b

誠にありがとうございます！

**Comment by tukiminya** [comment]
ご参考になったようで何よりです！
細かい点の指摘で申し訳なかったです...
こちらこそありがとうございました！

**Comment by YutaroOgawa** [comment]
@kr-tukimi さま

いえいえ、細かい点まで確認しながら、丁寧にご活用いただけ、とても嬉しいです。
本件、誠にありがとうございます。
