### ISSUE TITLE
4-2 確認時の画像サイズが縦に伸ばされている

### ISSUE THREAD

**Issue by tyfkda** [YutaroOgawa/pytorch_tutorials_jp#4]
４. 深層強化学習(Reinforcement Learning)
[2] 強化学習を用いたマリオの訓練
の日本語版追加の項目、訓練後の動作を動画で確認する際に
白黒およびカラーの場合に

```
plt.figure(figsize=(256/dpi,254/dpi),dpi=dpi)
```

としていますがファミコンの縦の解像度は `240` なので、わずかですが縦に引き伸ばされてしまっているようです
（環境の初期化の項の出力でも、`next_state.shape` は `(240, 256, 3)` となっています）。

`254` ではなく `240` ではないでしょうか？

**Comment by YutaroOgawa** [comment]
@tyfkda さま

ありがとうございます。
ご指摘いただいた通りです。

plt.figure(figsize=(256/dpi,254/dpi),dpi=dpi)
を
plt.figure(figsize=(240/dpi,256/dpi),dpi=dpi)

に修正いたしました。

https://github.com/YutaroOgawa/pytorch_tutorials_jp/tree/main/notebook/4_RL


ですが、今回のコードでは、
`class ResizeObservation(gym.ObservationWrapper):`

が効いてしまっていて、取り出した画像をimshowした場合、強制的に元の正方形を維持してしまっている状態です。

また、修正を考えます。

非常に丁寧な点を教えていただき、誠にありがとうございます。

**Comment by tyfkda** [comment]
@YutaroOgawa `figsize` に与えるパラメータは(縦, 横)なんですね、
また指定するサイズが実際の画像サイズの比率とずれていても引き伸ばされるわけではないようですね。失礼いたしました。
