### ISSUE TITLE
ソースコメントの日本語訳が一部おかしい

### ISSUE THREAD

**Issue by tyfkda** [YutaroOgawa/pytorch_tutorials_jp#5]
プレイしてみましょう！の段落のソースの20-21行目で、

```py
        # エージェントのインスタンス化
        action = mario.act(state)
```

となっていて、日本語コメントがおかしいように思います。
英語版では

```py
        # Run agent on the state
```

となっていますので、「エージェントを現在の状態で走らせる」などとされてはいかがでしょうか？

日本語版追加のコードも同様です。

**Comment by YutaroOgawa** [comment]
@tyfkda さま

誠にありがとうございます。

ご指摘の通りでございます。

コメントを


# 現在の状態に対するエージェントの行動を決める
action = mario.act(state)

へと変更して、リポジトリを更新いたしました。

誠にありがとうございます。
